databases:
  - name: military-db
    databaseName: military
    user: military_user
    plan: free # Note: Render Free Tier databases expire after 90 days.

services:
  # BACKEND (Django)
  - type: web
    name: military-backend
    runtime: python
    region: singapore # or ohio, frankfurt, etc.
    plan: free
    rootDir: server_django
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: military-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

  # FRONTEND (React)
  - type: static
    name: military-frontend
    runtime: static
    region: singapore
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    publishDir: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: military-backend
          property: url
